# Generated by Django 3.1.3 on 2022-07-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20220714_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
